import { isDevMode } from '@angular/core';

const BASE_URL_DEV = 'https://localhost:7283/api';
const BASE_URL_PROD = '';

const BASE_ENDPOINTS = {
  GET_ALL_CALCULATIONS: 'probability/calculations',  
  RUN_CALCULATION: 'probability/calculation'
};

const DEVELOPMENT_ENDPOINTS = {
  GET_ALL_CALCULATIONS: `${BASE_URL_DEV}/${BASE_ENDPOINTS.GET_ALL_CALCULATIONS}`,
  RUN_CALC: `${BASE_URL_DEV}/${BASE_ENDPOINTS.RUN_CALCULATION}`
};

const PRODUCTION_ENDPOINTS = {
  GET_ALL_CALCULATIONS: `${BASE_URL_PROD}/${BASE_ENDPOINTS.GET_ALL_CALCULATIONS}`,
  RUN_CALC: `${BASE_URL_PROD}/${BASE_ENDPOINTS.RUN_CALCULATION}`
};

const ENDPOINTS_TO_EXPORT = isDevMode() ? DEVELOPMENT_ENDPOINTS : PRODUCTION_ENDPOINTS;

export default ENDPOINTS_TO_EXPORT;
